server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  data:
    mongodb:
      uri:mongodb://root:root:@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
